package com.example.chaquitaclla_appmovil_android

object CountryCityData {
    val countries = mapOf(
        "USA" to 1,
        "Canada" to 2,
        "Mexico" to 3,
        "Brazil" to 4,
        "Argentina" to 5,
        "Germany" to 6,
        "France" to 7,
        "United Kingdom" to 8,
        "Italy" to 9,
        "Spain" to 10,
        "Russia" to 11,
        "China" to 12,
        "Japan" to 13,
        "India" to 14,
        "Australia" to 15,
        "South Africa" to 16,
        "Egypt" to 17,
        "Saudi Arabia" to 18,
        "South Korea" to 19,
        "Turkey" to 20,
        "Indonesia" to 21,
        "Thailand" to 22,
        "Malaysia" to 23,
        "Philippines" to 24,
        "Vietnam" to 25,
        "Netherlands" to 26,
        "Sweden" to 27,
        "Norway" to 28,
        "Finland" to 29,
        "Denmark" to 30,
        "Poland" to 31,
        "Ukraine" to 32,
        "Romania" to 33,
        "Hungary" to 34,
        "Portugal" to 35,
        "Greece" to 36,
        "Switzerland" to 37,
        "Belgium" to 38,
        "Austria" to 39,
        "New Zealand" to 40,
        "Chile" to 41,
        "Colombia" to 42,
        "Peru" to 43,
        "Venezuela" to 44,
        "Ecuador" to 45,
        "Bolivia" to 46,
        "Paraguay" to 47,
        "Uruguay" to 48,
        "Cuba" to 49,
        "Dominican Republic" to 50,

    )

    val cities = mapOf(
        1 to listOf("New York", "Los Angeles", "Chicago"),
        2 to listOf("Toronto", "Vancouver", "Montreal"),
        3 to listOf("Mexico City", "Guadalajara", "Monterrey"),
        4 to listOf("São Paulo", "Rio de Janeiro", "Brasilia"),
        5 to listOf("Buenos Aires", "Córdoba", "Rosario"),
        6 to listOf("Berlin", "Hamburg", "Munich"),
        7 to listOf("Paris", "Marseille", "Lyon"),
        8 to listOf("London", "Manchester", "Birmingham"),
        9 to listOf("Rome", "Milan", "Naples"),
        10 to listOf("Madrid", "Barcelona", "Valencia"),
        11 to listOf("Moscow", "Saint Petersburg", "Novosibirsk"),
        12 to listOf("Beijing", "Shanghai", "Shenzhen"),
        13 to listOf("Tokyo", "Osaka", "Yokohama"),
        14 to listOf("Mumbai", "Delhi", "Bangalore"),
        15 to listOf("Sydney", "Melbourne", "Brisbane"),
        16 to listOf("Cape Town", "Johannesburg", "Durban"),
        17 to listOf("Cairo", "Alexandria", "Giza"),
        18 to listOf("Riyadh", "Jeddah", "Mecca"),
        19 to listOf("Seoul", "Busan", "Incheon"),
        20 to listOf("Istanbul", "Ankara", "Izmir"),
        21 to listOf("Jakarta", "Surabaya", "Bandung"),
        22 to listOf("Bangkok", "Chiang Mai", "Pattaya"),
        23 to listOf("Kuala Lumpur", "George Town", "Johor Bahru"),
        24 to listOf("Manila", "Cebu", "Davao"),
        25 to listOf("Ho Chi Minh City", "Hanoi", "Da Nang"),
        26 to listOf("Amsterdam", "Rotterdam", "The Hague"),
        27 to listOf("Stockholm", "Gothenburg", "Malmö"),
        28 to listOf("Oslo", "Bergen", "Stavanger"),
        29 to listOf("Helsinki", "Espoo", "Tampere"),
        30 to listOf("Copenhagen", "Aarhus", "Odense"),
        31 to listOf("Warsaw", "Kraków", "Łódź"),
        32 to listOf("Kyiv", "Lviv", "Odessa"),
        33 to listOf("Bucharest", "Cluj-Napoca", "Timișoara"),
        34 to listOf("Budapest", "Debrecen", "Szeged"),
        35 to listOf("Lisbon", "Porto", "Amadora"),
        36 to listOf("Athens", "Thessaloniki", "Patras"),
        37 to listOf("Zurich", "Geneva", "Basel"),
        38 to listOf("Brussels", "Antwerp", "Ghent"),
        39 to listOf("Vienna", "Salzburg", "Innsbruck"),
        40 to listOf("Auckland", "Wellington", "Christchurch"),
        41 to listOf("Santiago", "Valparaíso", "Concepción"),
        42 to listOf("Bogotá", "Medellín", "Cali"),
        43 to listOf("Lima", "Arequipa", "Trujillo"),
        44 to listOf("Caracas", "Maracaibo", "Valencia"),
        45 to listOf("Quito", "Guayaquil", "Cuenca"),
        46 to listOf("La Paz", "Santa Cruz", "Cochabamba"),
        47 to listOf("Asunción", "Ciudad del Este", "Encarnación"),
        48 to listOf("Montevideo", "Salto", "Paysandú"),
        49 to listOf("Havana", "Santiago de Cuba", "Camagüey"),
        50 to listOf("Santo Domingo", "Santiago de los Caballeros", "La Vega")
    )
}